from django.core.exceptions import ValidationError
from django.test import TestCase


class MixinsTestCase(TestCase):
    pass
